driver:
  name: vagrant

platforms:
  - name: centos-7.3

provisioner:
  name: salt_solo
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  salt_install: bootstrap
  is_file_root: True
  state_top_from_file: True
  pillars-from-files:
    users.sls: test_pillar/users.sls
  pillars:
    top.sls:
      base:
        '*':
          - users
suites:
  - name: default
  - name: web
    provisioner:
      grains:
        role:
          - development
          - web
  - name: logger
    provisioner:
      grains:
        role:
          - logger

verifier:
  name: shell
  command: python3 /usr/local/bin/testinfra -vvv test/integration/$KITCHEN_SUITE
