driver:
  name: vagrant

platforms:
  - name: centos-6.9

provisioner:
  name: salt_solo
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  salt_install: bootstrap
  is_file_root: True
  state_top_from_file: True
  pillars-from-files:
    users.sls: test_pillar/users.sls
  pillars:
    top.sls:
      base:
        '*':
          - users
suites:
  - name: default
  - name: web01
  - name: web02